using CG.CqrsCrud.Attributes.Commons;
using System.Reflection;

namespace CG.CqrsCrud.Generators
{
    public static class AddMediatorGenerator<T>
    {
        public static bool GenerateAddMediator(string plural, string commandNameSpace, string commandPath)
        {
            List<string> command = new List<string>();
            command.Add("using MediatR;");
            command.Add("");
            command.Add($"namespace {commandNameSpace}.{plural};");
            command.Add("");
            command.Add($"public class Add{typeof(T).Name}Command : IRequest<bool>");
            command.Add("{");
            foreach (PropertyInfo info in typeof(T).GetProperties())
            {
                if (info.SetMethod == null || info.GetCustomAttributes().Where(x=>x is AutoGeneratedPrimaryKey).Any())
                {
                    continue;
                }
                command.Add($"\tpublic {info.PropertyType.Name} {info.Name} {{ get; set;}}");
            }
            command.Add("}");
            File.WriteAllLines($"{commandPath}\\Add{typeof(T).Name}Command.cs", command);

            List<string> commandHandler = new List<string>();
            commandHandler.Add("using MediatR;");
            commandHandler.Add("");
            commandHandler.Add($"namespace {commandNameSpace}.{plural};");
            commandHandler.Add("");
            commandHandler.Add($"public class Add{typeof(T).Name}CommandHandler : IRequestHandler<Add{typeof(T).Name}Command, bool>");
            commandHandler.Add("{");
            commandHandler.Add($"\tprivate readonly I{typeof(T).Name}Repository _{typeof(T).Name.ToLower()}Repository;");
            commandHandler.Add($"\tpublic Add{typeof(T).Name}CommandHandler(I{typeof(T).Name}Repository {typeof(T).Name.ToLower()}Repository)");
            commandHandler.Add("\t{");
            commandHandler.Add($"\t\t_{typeof(T).Name.ToLower()}Repository = {typeof(T).Name.ToLower()}Repository;");
            commandHandler.Add("\t}");
            commandHandler.Add("\t");
            commandHandler.Add($"\tpublic async Task<bool> Handle(Add{typeof(T).Name}Command request, CancellationToken cancellationToken)");
            commandHandler.Add("\t{");
            commandHandler.Add($"\t\tvar {typeof(T).Name.ToLower()} = new {typeof(T).Name}");
            commandHandler.Add("\t\t{");
            foreach (PropertyInfo info in typeof(T).GetProperties())
            {
                if (info.SetMethod == null || info.GetCustomAttributes().Where(x => x is AutoGeneratedPrimaryKey).Any())
                {
                    continue;
                }
                commandHandler.Add($"\t\t\t{info.Name} = request.{info.Name},");
            }
            commandHandler.Add("\t\t};");
            commandHandler.Add("\t\t");
            commandHandler.Add($"\t\treturn await _{typeof(T).Name.ToLower()}Repository.Add{typeof(T).Name}({typeof(T).Name.ToLower()});");
            commandHandler.Add("\t}");
            commandHandler.Add("}");
            File.WriteAllLines($"{commandPath}\\Add{typeof(T).Name}Command.Handler.cs", commandHandler);

            return true;
        }
    }
}
